'use server';

import { createClient } from '@/utils/supabase/server';
import { encodedRedirect } from '@/utils/redirect';
import { headers } from 'next/headers';
import { redirect } from 'next/navigation';
import { prisma, withRetry, ensureConnection } from '@/lib/db-unified';
import { resolveRequestOrigin } from '@/lib/auth/site-origin';
import { UserRole } from '@prisma/client'; // Assuming UserRole enum is generated by Prisma

const PROFILE_SETUP_FAILED_MESSAGE = 'User profile could not be created. Please contact support.';

/** Prisma P2002 on the `profiles.email` unique index. */
function isEmailUniqueViolation(error: unknown): boolean {
  const e = error as { code?: string; meta?: { target?: unknown } } | null;
  if (e?.code !== 'P2002') return false;
  const target = e.meta?.target;
  return Array.isArray(target) ? target.includes('email') : String(target ?? '').includes('email');
}

/**
 * Whether `userId` still resolves to an auth user. Uses the service-role
 * client lazily so the ordinary sign-in path never loads it. Fails closed:
 * if the check cannot run, the id is treated as live.
 */
async function isLiveAuthUser(userId: string): Promise<boolean> {
  try {
    const { supabaseAdmin } = await import('@/lib/supabase/admin');
    const { data, error } = await supabaseAdmin.auth.admin.getUserById(userId);
    if (error) {
      // Only Supabase's own "no such user" answer proves absence. Any other
      // 404 (a misrouted NEXT_PUBLIC_SUPABASE_URL) is unknown state.
      return !(error.status === 404 && error.code === 'user_not_found');
    }
    return Boolean(data?.user);
  } catch (error) {
    console.error('isLiveAuthUser: admin lookup unavailable, failing closed:', error);
    return true;
  }
}

/**
 * Whether an existing `profiles` row may be re-pointed at `userId`.
 * Never an ADMIN row (those are linked by an admin tool, not by whoever
 * registers the address), and never a row whose current id is still a live
 * auth user (someone who changed their login email and left the row behind).
 */
async function canAdoptProfile(
  row: { id: string; role: UserRole },
  userId: string
): Promise<boolean> {
  if (row.role === UserRole.ADMIN) return false;
  if (row.id === userId) return true;
  return !(await isLiveAuthUser(row.id));
}

const EMAIL_ALREADY_REGISTERED_MESSAGE =
  'This email is already registered. Please sign in instead.';
const PROFILE_LINK_REFUSED_MESSAGE =
  'This email is already associated with an existing account. Please contact support.';

export const signUpAction = async (formData: FormData) => {
  const email = formData.get('email') as string;
  const password = formData.get('password') as string;
  const name = formData.get('name') as string;
  const phone = formData.get('phone') as string;
  // No sign-up form sends an `origin` field; reading one produced the dead
  // verification link "null/auth/callback". Resolve it like forgotPasswordAction.
  const origin = resolveRequestOrigin((await headers()).get('origin'));

  if (!email || !password) {
    return { error: 'Email and password are required.' };
  }

  const supabase = await createClient();

  // Check if profile already exists (for seeded admin case)
  let existingProfile = null;
  try {
    existingProfile = await withRetry(
      async () => {
        return await prisma.profile.findUnique({
          where: { email },
          select: { id: true, role: true, email: true },
        });
      },
      3,
      'signUpAction_checkExistingProfile'
    );
  } catch (profileError) {
    console.error('Error checking existing profile:', profileError);
    // Continue with sign up even if profile check fails
  }

  // Try to sign in first (user might already exist)
  const { error: signInError } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (signInError) {
    // If sign in failed, it might be because the Supabase user doesn't exist yet
    // but the profile does (seeded admin case)
  }

  const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
    email,
    password,
    options: {
      emailRedirectTo: `${origin}/auth/callback`,
    },
  });

  if (signUpError) {
    console.error('Supabase SignUp Error:', signUpError);
    if (signUpError.message.includes('User already registered')) {
      return { error: 'This email is already registered. Please sign in instead.' };
    }
    return { error: `Sign up failed: ${signUpError.message}` };
  }

  if (!signUpData.user) {
    console.error('Supabase SignUp Error: User data missing after sign up.');
    return { error: 'Sign up process failed unexpectedly. Could not retrieve user information.' };
  }

  // With email confirmation on, Supabase answers a sign-up for an address that
  // is already registered with HTTP 200 and a placeholder user: a fresh random
  // id and no identities. Linking a profile to that id would orphan the real
  // owner, so stop here.
  if (!signUpData.user.identities || signUpData.user.identities.length === 0) {
    return { error: EMAIL_ALREADY_REGISTERED_MESSAGE };
  }

  const userId = signUpData.user.id;

  try {
    if (existingProfile) {
      if (!(await canAdoptProfile(existingProfile, userId))) {
        console.error(
          `Sign-up: refusing to link existing profile ${existingProfile.id} to ${userId}`
        );
        return { error: PROFILE_LINK_REFUSED_MESSAGE };
      }
      // Update existing profile to link it with the new Supabase user ID
      await withRetry(
        async () => {
          return await prisma.profile.update({
            where: { id: existingProfile.id },
            data: {
              id: userId,
              name: name || existingProfile.email.split('@')[0], // Use provided name or email prefix
              phone: phone,
              updated_at: new Date(),
            },
          });
        },
        3,
        'signUpAction_updateExistingProfile'
      );
      console.log(`Linked existing profile for ${email} to Supabase user ${userId}`);
    } else {
      await withRetry(
        async () => {
          return await prisma.profile.upsert({
            where: { id: userId },
            create: {
              id: userId,
              email,
              name: name || null,
              phone: phone || null,
              role: UserRole.CUSTOMER,
              updated_at: new Date(),
            },
            update: {
              name: name || undefined,
              phone: phone || undefined,
              updated_at: new Date(),
            },
          });
        },
        3,
        'signUpAction_upsertProfile'
      );

      console.log(`Profile upserted for ${email}`);
    }
  } catch (profileError: any) {
    const isConnectionError =
      profileError.message?.includes('Timed out') ||
      profileError.message?.includes('ECONNRESET') ||
      profileError.message?.includes('Connection') ||
      profileError.code === 'P1001' ||
      profileError.code === 'P1008' ||
      profileError.code === 'P2024';
    console.error(
      `Prisma profile ${isConnectionError ? 'connection' : 'creation/update'} error during sign up:`,
      { code: profileError.code, message: profileError.message }
    );

    if (isEmailUniqueViolation(profileError)) {
      try {
        const collided = await prisma.profile.findUnique({
          where: { email },
          select: { id: true, role: true },
        });
        if (!collided || !(await canAdoptProfile(collided, userId))) {
          console.error(`Sign-up: refusing to link colliding profile for user ${userId}`);
          return { error: PROFILE_LINK_REFUSED_MESSAGE };
        }
        await prisma.profile.update({
          where: { id: collided.id },
          data: {
            id: userId,
            updated_at: new Date(),
          },
        });
        console.log(`Linked existing profile for ${email} with new user ID`);
      } catch (updateError) {
        console.error('Failed to link existing profile:', updateError);
        return { error: `Account created, but profile linking failed. Please contact support.` };
      }
    } else {
      return {
        error: `Account created, but profile setup failed: ${profileError.message}. Please contact support.`,
      };
    }
  }

  return { success: 'Sign up successful! Please check your email for verification.' };
};

export const signInAction = async (formData: FormData) => {
  const email = formData.get('email') as string;
  const password = formData.get('password') as string;
  const redirectUrl = formData.get('redirect') as string;
  const supabase = await createClient();

  const { error: signInError } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (signInError) {
    return encodedRedirect('error', '/sign-in', signInError.message);
  }

  // After successful sign-in, get user and their profile
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    // Should not happen after successful sign-in, but handle defensively
    return encodedRedirect('error', '/sign-in', 'Could not retrieve user after sign in.');
  }

  let profile: { role: UserRole } | null = null;
  let profileFetchError: any = null; // Use 'any' or a more specific error type if known

  try {
    // Try block ONLY for prisma query with robust connection management
    profile = await withRetry(
      async () => {
        return await prisma.profile.findUnique({
          where: { id: user.id },
          select: { role: true }, // Only select the role field
        });
      },
      3,
      'signInAction_findProfile'
    );
  } catch (dbError) {
    // Catch ONLY potential database errors
    profileFetchError = dbError; // Store the error
    console.error('Prisma profile fetch error:', JSON.stringify(dbError, null, 2));
    // Redirect immediately if the database query itself fails
    return encodedRedirect('error', '/sign-in', 'Database error retrieving user profile.');
  }

  if (!profile) {
    console.error(`Sign-in: Profile not found for user ${user.id}, creating one`);

    const authName = user.user_metadata?.name as string | undefined;
    const authPhone = user.user_metadata?.phone as string | undefined;

    try {
      profile = await withRetry(
        async () => {
          return await prisma.profile.upsert({
            where: { id: user.id },
            update: {},
            create: {
              id: user.id,
              email: user.email || email,
              name: authName || null,
              phone: authPhone || null,
              role: UserRole.CUSTOMER,
              updated_at: new Date(),
            },
            select: { role: true },
          });
        },
        3,
        'signInAction_upsertProfile'
      );
    } catch (createError) {
      if (!isEmailUniqueViolation(createError)) {
        console.error(`Failed to create profile for user ${user.id} during sign-in:`, createError);
        return encodedRedirect('error', '/sign-in', PROFILE_SETUP_FAILED_MESSAGE);
      }

      // A profile row already exists for this email under a different id
      // (seeded or pre-migration data). Without a relink the user is locked
      // out for good: every sign-in retries the same unique violation.
      //
      // Guards: the relink is keyed on the auth user's own verified email
      // (never the submitted form value), requires a confirmed email, and
      // never adopts an ADMIN row on sign-in, so a stray admin seed cannot be
      // claimed by whoever registers that address. Admin rows are linked
      // through the sign-up flow or by hand.
      if (!user.email || !user.email_confirmed_at) {
        console.error(
          `Sign-in: refusing profile relink for ${user.id}: email missing or unconfirmed`
        );
        return encodedRedirect('error', '/sign-in', PROFILE_SETUP_FAILED_MESSAGE);
      }

      try {
        const orphan = await prisma.profile.findUnique({
          where: { email: user.email },
          select: { id: true, role: true },
        });

        if (!orphan) {
          console.error(`Sign-in: refusing profile relink for ${user.id}: no row found by email`);
          return encodedRedirect('error', '/sign-in', PROFILE_SETUP_FAILED_MESSAGE);
        }

        if (orphan.id === user.id) {
          // A concurrent sign-in already relinked it.
          profile = { role: orphan.role };
        } else {
          if (!(await canAdoptProfile(orphan, user.id))) {
            console.error(
              `Sign-in: refusing profile relink for ${user.id}: row ${orphan.id} is ADMIN or still owned`
            );
            return encodedRedirect('error', '/sign-in', PROFILE_SETUP_FAILED_MESSAGE);
          }

          try {
            profile = await withRetry(
              async () =>
                prisma.profile.update({
                  where: { id: orphan.id },
                  data: { id: user.id, updated_at: new Date() },
                  select: { role: true },
                }),
              3,
              'signInAction_relinkProfile'
            );
            console.warn(`Sign-in: relinked orphaned profile ${orphan.id} to auth user ${user.id}`);
          } catch (updateError) {
            // P2025: the row vanished under its old id because a concurrent
            // sign-in relinked it first. Re-read under the new id.
            const code = (updateError as { code?: string } | null)?.code;
            const relinked =
              code === 'P2025'
                ? await prisma.profile.findUnique({
                    where: { id: user.id },
                    select: { role: true },
                  })
                : null;
            if (!relinked) throw updateError;
            profile = relinked;
          }
        }
      } catch (relinkError) {
        console.error(`Failed to relink profile for user ${user.id} during sign-in:`, relinkError);
        return encodedRedirect('error', '/sign-in', PROFILE_SETUP_FAILED_MESSAGE);
      }
    }
  }

  // Profile fetched or created successfully, perform redirect based on role and redirect parameter
  if (profile.role === UserRole.ADMIN) {
    // Use Prisma enum for role comparison
    return redirect('/admin');
  } else {
    // For non-admin users, use the redirect URL if provided, otherwise default to menu
    return redirect(redirectUrl || '/menu');
  }
};

export const forgotPasswordAction = async (formData: FormData) => {
  const email = formData.get('email')?.toString();
  const supabase = await createClient();
  // An absent `origin` header used to stringify to "null", producing the dead
  // link "null/auth/callback" in the outbound email.
  const origin = resolveRequestOrigin((await headers()).get('origin'));
  const callbackUrl = formData.get('callbackUrl')?.toString();

  if (!email) {
    return encodedRedirect('error', '/forgot-password', 'Email is required');
  }

  const { error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: `${origin}/auth/callback?redirect_to=/protected/reset-password`,
  });

  if (error) {
    console.error(error.message);
    return encodedRedirect('error', '/forgot-password', 'Could not reset password');
  }

  if (callbackUrl) {
    return redirect(callbackUrl);
  }

  return encodedRedirect(
    'success',
    '/forgot-password',
    'Check your email for a link to reset your password.'
  );
};

export const resetPasswordAction = async (formData: FormData) => {
  const supabase = await createClient();

  const password = formData.get('password') as string;
  const confirmPassword = formData.get('confirmPassword') as string;

  if (!password || !confirmPassword) {
    return encodedRedirect(
      'error',
      '/protected/reset-password',
      'Password and confirm password are required'
    );
  }

  if (password !== confirmPassword) {
    return encodedRedirect('error', '/protected/reset-password', 'Passwords do not match');
  }

  const { error } = await supabase.auth.updateUser({
    password: password,
  });

  if (error) {
    return encodedRedirect('error', '/protected/reset-password', 'Password update failed');
  }

  // Redirect to account page with success message
  return encodedRedirect('success', '/account', 'Your password has been updated successfully');
};

export const setupPasswordAction = async (formData: FormData) => {
  const password = formData.get('password') as string;
  const confirmPassword = formData.get('confirmPassword') as string;
  const supabase = await createClient();

  // Validate password requirements
  if (!password || !confirmPassword) {
    return encodedRedirect(
      'error',
      '/setup-password',
      'Password and confirm password are required'
    );
  }

  if (password !== confirmPassword) {
    return encodedRedirect('error', '/setup-password', 'Passwords do not match');
  }

  // Validate password strength
  const passwordRequirements = [
    {
      test: (pwd: string) => pwd.length >= 8,
      message: 'Password must be at least 8 characters long',
    },
    {
      test: (pwd: string) => /[A-Z]/.test(pwd),
      message: 'Password must contain an uppercase letter',
    },
    {
      test: (pwd: string) => /[a-z]/.test(pwd),
      message: 'Password must contain a lowercase letter',
    },
    { test: (pwd: string) => /\d/.test(pwd), message: 'Password must contain a number' },
    {
      test: (pwd: string) => /[!@#$%^&*(),.?":{}|<>]/.test(pwd),
      message: 'Password must contain a special character',
    },
  ];

  for (const requirement of passwordRequirements) {
    if (!requirement.test(password)) {
      return encodedRedirect('error', '/setup-password', requirement.message);
    }
  }

  // Get current user (should be authenticated via invitation link)
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return encodedRedirect(
      'error',
      '/setup-password',
      'Authentication required. Please use the invitation link.'
    );
  }

  // Update the user's password
  const { error: updateError } = await supabase.auth.updateUser({
    password: password,
  });

  if (updateError) {
    console.error('Password setup error:', updateError);
    return encodedRedirect(
      'error',
      '/setup-password',
      'Failed to set up password. Please try again.'
    );
  }

  // Check if user has a profile, if not create one
  try {
    const existingProfile = await prisma.profile.findUnique({
      where: { id: user.id },
    });

    if (!existingProfile) {
      // Create profile if it doesn't exist (shouldn't happen with admin-created users, but safety check)
      await prisma.profile.create({
        data: {
          id: user.id,
          email: user.email!,
          name: user.user_metadata?.name || null,
          phone: user.user_metadata?.phone || null,
          role: UserRole.CUSTOMER,
        },
      });
    }
  } catch (profileError) {
    console.error('Profile check/creation error during password setup:', profileError);
    // Don't fail the password setup for profile issues, just log it
  }

  // Redirect to sign-in with success message
  return encodedRedirect(
    'success',
    '/sign-in',
    'Password set up successfully! You can now sign in with your new password.'
  );
};

export const signOutAction = async () => {
  const supabase = await createClient();
  await supabase.auth.signOut();
  return redirect('/sign-in');
};

export const magicLinkSignInAction = async (formData: FormData) => {
  const email = formData.get('email')?.toString();
  const supabase = await createClient();
  // An absent `origin` header used to stringify to "null", producing the dead
  // link "null/auth/callback" in the outbound email.
  const origin = resolveRequestOrigin((await headers()).get('origin'));
  const redirectUrl = formData.get('redirect')?.toString();

  if (!email) {
    return encodedRedirect('error', '/sign-in', 'Email is required');
  }

  // Check if user exists in our database
  let existingProfile;
  try {
    existingProfile = await prisma.profile.findUnique({
      where: { email },
      select: { id: true, email: true, role: true },
    });
  } catch (dbError) {
    console.error('Database error during magic link profile lookup:', dbError);
    return encodedRedirect('error', '/sign-in', 'Database error. Please try again.');
  }

  if (!existingProfile) {
    return encodedRedirect(
      'error',
      '/sign-in',
      'No account found with this email. Please sign up first or use a different email.'
    );
  }

  // Determine redirect destination based on role and redirect parameter
  let redirectTo = '/menu'; // default for customers
  if (existingProfile.role === 'ADMIN') {
    redirectTo = '/admin';
  } else if (redirectUrl) {
    redirectTo = redirectUrl;
  }

  console.log('🪄 Sending magic link:', {
    email,
    origin,
    redirectTo,
    fullRedirectUrl: `${origin}/auth/callback?redirect_to=${redirectTo}`,
  });

  // Send magic link using OTP flow
  const { error } = await supabase.auth.signInWithOtp({
    email,
    options: {
      emailRedirectTo: `${origin}/auth/callback?redirect_to=${redirectTo}`,
      // Ensure this is treated as a magic link OTP, not PKCE
      shouldCreateUser: false, // Don't create new users through magic link
    },
  });

  if (error) {
    console.error('Magic link error:', error.message);

    // Provide more specific error messages
    if (error.message.includes('email not confirmed')) {
      return encodedRedirect('error', '/sign-in', 'Please verify your email address first.');
    } else if (error.message.includes('signup')) {
      return encodedRedirect('error', '/sign-in', 'Account not found. Please sign up first.');
    } else {
      return encodedRedirect('error', '/sign-in', 'Could not send magic link. Please try again.');
    }
  }

  console.log('✅ Magic link sent successfully to:', email);

  return encodedRedirect('success', '/sign-in', 'Check your email for a magic link to sign in!');
};

/**
 * Server Action to safely get authenticated user profile
 * This handles cookie operations properly within a Server Action context
 */
export async function getAuthenticatedUserProfile(): Promise<{
  isLoggedIn: boolean;
  userData: {
    id: string;
    name: string;
    email: string;
    phone: string;
  } | null;
  error: string | null;
}> {
  try {
    // Create Supabase client within Server Action context - this safely handles cookies
    const supabase = await createClient();

    // This call may trigger a token refresh and cookie setting, but it's safe in Server Actions
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return {
        isLoggedIn: false,
        userData: null,
        error: authError?.message || 'User not authenticated',
      };
    }

    // Fetch user profile from database with robust connection management
    try {
      const profile = await withRetry(
        async () => {
          return await prisma.profile.findUnique({
            where: { id: user.id },
            select: {
              id: true,
              name: true,
              email: true,
              phone: true,
            },
          });
        },
        3,
        'getAuthenticatedUserProfile'
      );

      if (!profile) {
        return {
          isLoggedIn: false,
          userData: null,
          error: 'User profile not found',
        };
      }

      return {
        isLoggedIn: true,
        userData: {
          id: profile.id,
          name: profile.name || '',
          email: profile.email || user.email || '',
          phone: profile.phone || '',
        },
        error: null,
      };
    } catch (dbError) {
      console.error('Database error fetching user profile:', dbError);

      // Fallback to auth user data if database fails
      return {
        isLoggedIn: true,
        userData: {
          id: user.id,
          name: user.user_metadata?.full_name || user.user_metadata?.name || '',
          email: user.email || '',
          phone: user.phone || user.user_metadata?.phone || '',
        },
        error: null,
      };
    }
  } catch (error) {
    console.error('Error in getAuthenticatedUserProfile:', error);
    return {
      isLoggedIn: false,
      userData: null,
      error: 'Failed to fetch user profile',
    };
  }
}
